# Generated by Django 5.0 on 2023-12-12 08:37

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_model',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.TextField(max_length=20)),
                ('desc', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='domain_model',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.TextField(max_length=30)),
                ('desc', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_model',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teacher_id', models.PositiveIntegerField()),
                ('phone_number', models.PositiveBigIntegerField()),
                ('year_of_experience', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='course_video_model',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('v_title', models.CharField(max_length=20)),
                ('v_text', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course_model')),
            ],
        ),
        migrations.AddField(
            model_name='course_model',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.domain_model'),
        ),
    ]
