# Generated by Django 5.0 on 2023-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_model',
            name='price',
            field=models.BigIntegerField(default=1000),
        ),
    ]
