# Generated by Django 5.0 on 2023-12-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain_model',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.TextField(max_length=30)),
                ('desc', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='course_model',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.TextField(max_length=20)),
                ('desc', models.TextField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.domain_model')),
            ],
        ),
    ]
