# Generated by Django 5.0 on 2023-12-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_domain_model_course_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_model',
            name='file1',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_model',
            name='desc',
            field=models.TextField(max_length=100),
        ),
    ]
