# Generated by Django 5.0 on 2023-12-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_course_model_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='course_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course_video_model',
            name='v_text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='domain_model',
            name='desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='domain_model',
            name='domain_name',
            field=models.CharField(max_length=300),
        ),
    ]
