# Generated by Django 5.0 on 2023-12-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_course_model_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_model',
            name='tid',
            field=models.PositiveSmallIntegerField(default=11),
        ),
    ]
