# Generated by Django 5.0 on 2023-12-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_course_model_file1_alter_course_model_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='file1',
            field=models.CharField(max_length=500),
        ),
    ]
