# Generated by Django 5.0 on 2023-12-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_course_model_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_model',
            name='payment',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
