# Generated by Django 5.0 on 2023-12-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_course_model_file1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_model',
            name='file1',
        ),
    ]
