# Generated by Django 5.0 on 2023-12-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_course_model_file1'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_video_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_title', models.CharField(max_length=20)),
                ('v_text', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course_model')),
            ],
        ),
    ]
