# Generated by Django 5.0 on 2023-12-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_model_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_model',
            name='payment',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
