# Generated by Django 5.0 on 2023-12-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_course_video_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_video_model',
            name='id',
        ),
        migrations.AddField(
            model_name='course_video_model',
            name='vid',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
