# Generated by Django 5.0 on 2023-12-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teacher_model_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveBigIntegerField()),
                ('sid', models.PositiveBigIntegerField()),
                ('tid', models.PositiveBigIntegerField()),
                ('schat', models.CharField(max_length=512)),
                ('tchat', models.CharField(max_length=512)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='chat_images/')),
                ('file', models.FileField(upload_to='chat_Docs/')),
            ],
        ),
    ]
