# Generated by Django 5.0 on 2023-12-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_remove_course_video_model_id_course_video_model_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_video_model',
            name='vid',
        ),
        migrations.AddField(
            model_name='course_video_model',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
