# Generated by Django 5.0 on 2023-12-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_chat_model_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_video_model',
            name='tid',
            field=models.PositiveSmallIntegerField(default=11),
        ),
    ]
