# Generated by Django 5.0 on 2023-12-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_course_video_model_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_model',
            name='file',
            field=models.FileField(null=True, upload_to='chat_Docs/'),
        ),
        migrations.AlterField(
            model_name='chat_model',
            name='image',
            field=models.ImageField(null=True, upload_to='chat_images/'),
        ),
    ]
