# Generated by Django 5.0 on 2023-12-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_chat_model_file_alter_chat_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_model',
            name='chat_id',
        ),
    ]
