# Generated by Django 5.0 on 2023-12-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_remove_chat_model_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_model',
            old_name='file',
            new_name='sfile',
        ),
        migrations.RenameField(
            model_name='chat_model',
            old_name='image',
            new_name='simage',
        ),
        migrations.AddField(
            model_name='chat_model',
            name='tfile',
            field=models.FileField(null=True, upload_to='chat_Docs/'),
        ),
        migrations.AddField(
            model_name='chat_model',
            name='timage',
            field=models.ImageField(null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='chat_model',
            name='course_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
