# Generated by Django 5.0 on 2023-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_buy_course_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_course_model',
            name='bought_date',
            field=models.DateField(auto_now=True),
        ),
    ]
