# Generated by Django 5.0 on 2023-12-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_buy_course_model_bought_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy_course_model',
            options={},
        ),
        migrations.AlterModelManagers(
            name='buy_course_model',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='buy_course_model',
            name='user_ptr',
        ),
    ]
