# Generated by Django 5.0 on 2023-12-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_buy_course_model_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_course_model',
            old_name='order_name',
            new_name='course_id',
        ),
    ]
