# Generated by Django 5.0 on 2023-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_order_name_buy_course_model_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_course_model',
            name='course_id',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
