# Generated by Django 5.0 on 2023-12-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_buy_course_model_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_course_model',
            name='sid',
            field=models.PositiveIntegerField(max_length=30),
        ),
    ]
