# Generated by Django 5.0 on 2023-12-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_buy_course_model_bought_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_course_model',
            old_name='order_id',
            new_name='orderid',
        ),
    ]
