# Generated by Django 5.0 on 2023-12-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_delete_buy_course_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_course_model',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('stud_id', models.PositiveBigIntegerField()),
                ('course_id', models.PositiveBigIntegerField()),
                ('bougth_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
