# Generated by Django 5.0 on 2023-12-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_buy_course_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='opt_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_no', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
