# Generated by Django 5.0 on 2023-12-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_rename_opt_model_otp_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_course_model',
            name='teacher_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
